version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourusername/epitopegraph:api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: uvicorn epitopegraph.api.server:app --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourusername/epitopegraph:jupyter
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 