name: epitopegraph
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - biopython>=1.79
  - requests>=2.26.0
  - requests-cache>=0.8.0
  - tqdm>=4.62.0
  - nglview>=2.7.0
  - jupyter>=1.0.0
  - jupyterlab>=3.2.0
  - pytorch>=1.10.0
  - torch-geometric>=2.0.0
  - cudatoolkit>=11.3
  - pip:
    - epitopegraph
    - black>=21.12b0
    - isort>=5.10.0
    - flake8>=4.0.0
    - mypy>=0.910
    - pytest>=6.2.5
    - pytest-cov>=2.12.0
    - pre-commit>=2.15.0
    - sphinx>=4.3.0
    - sphinx-rtd-theme>=1.0.0
    - myst-parser>=0.15.0
    - nbsphinx>=0.8.0
    - sphinx-copybutton>=0.4.0 